from Products.ERP5Type.Message import translateString

if context.getGlobalConfigurationAttr('categories_spreadsheet_configuration_save_relative_url'):
  item_list_from_spreadsheet = context.BusinessConfiguration_getCategoriesSpreadsheetConfiguratorItem().getCategoryTitleItemList('region')
  if item_list_from_spreadsheet != [('', '')]:
    return item_list_from_spreadsheet

region_item_list = [
  (b'Afghanistan', 'asia/southern_asia/afghanistan'),
  (b'Albania', 'europe/southern_europe/albania'),
  (b'Algeria', 'africa/northern_africa/algeria'),
  (b'American Samoa', 'oceania/polynesia/american_samoa'),
  (b'Andorra', 'europe/southern_europe/andorra'),
  (b'Angola', 'africa/middle_africa/angola'),
  (b'Anguilla', 'americas/caribbean/anguilla'),
  (b'Antigua and Barbuda', 'americas/caribbean/antigua_and_barbuda'),
  (b'Argentina', 'americas/south_america/argentina'),
  (b'Armenia', 'asia/western_asia/armenia'),
  (b'Aruba', 'americas/caribbean/aruba'),
  (b'Australia', 'oceania/australia/australia'),
  (b'Austria', 'europe/western_europe/austria'),
  (b'Azerbaijan', 'asia/western_asia/azerbaijan'),
  (b'Bahamas', 'americas/caribbean/bahamas'),
  (b'Bahrain', 'asia/western_asia/bahrain'),
  (b'Bangladesh', 'asia/southern_asia/bangladesh'),
  (b'Barbados', 'americas/caribbean/barbados'),
  (b'Belarus', 'europe/eastern_europe/belarus'),
  (b'Belgium', 'europe/western_europe/belgium'),
  (b'Belize', 'americas/central_america/belize'),
  (b'Benin', 'africa/western_africa/benin'),
  (b'Bermuda', 'americas/northern_america/bermuda'),
  (b'Bhutan', 'asia/southern_asia/bhutan'),
  (b'Bolivia', 'americas/south_america/bolivia'),
  (b'Bosnia and Herzegovina', 'europe/southern_europe/bosnia_and_herzegovina'),
  (b'Botswana', 'africa/southern_africa/botswana'),
  (b'Brazil', 'americas/south_america/brazil'),
  (b'British Virgin Islands', 'americas/caribbean/british_virgin_islands'),
  (b'Brunei Darussalam', 'asia/south-eastern_asia/brunei_darussalam'),
  (b'Bulgaria', 'europe/eastern_europe/bulgaria'),
  (b'Burkina Faso', 'africa/western_africa/burkina_faso'),
  (b'Burundi', 'africa/eastern_africa/burundi'),
  (b'Cambodia', 'asia/south-eastern_asia/cambodia'),
  (b'Cameroon', 'africa/middle_africa/cameroon'),
  (b'Canada', 'americas/northern_america/canada'),
  (b'Cape Verde', 'africa/western_africa/cape_verde'),
  (b'Cayman Islands', 'americas/caribbean/cayman_islands'),
  (b'Central African Republic', 'africa/middle_africa/central_african_republic'),
  (b'Chad', 'africa/middle_africa/chad'),
  (b'Channel Islands', 'europe/northern_europe/channel_islands'),
  (b'Chile', 'americas/south_america/chile'),
  (b'China', 'asia/eastern_asia/china'),
  (b'Colombia', 'americas/south_america/colombia'),
  (b'Comoros', 'africa/eastern_africa/comoros'),
  (b'Congo', 'africa/middle_africa/congo'),
  (b'Cook Islands', 'oceania/polynesia/cook_islands'),
  (b'Costa Rica', 'americas/central_america/costa_rica'),
  (b"Cote d'Ivoire", 'africa/western_africa/cote_diivoire'),
  (b'Croatia', 'europe/southern_europe/croatia'),
  (b'Cuba', 'americas/caribbean/cuba'),
  (b'Cyprus', 'asia/western_asia/cyprus'),
  (b'Czech Republic', 'europe/eastern_europe/czech_republic'),
  (b"Democratic People's Republic of Korea", 'asia/eastern_asia/democratic_peoples_republic_of_korea'),
  (b'Democratic Republic of the Congo', 'africa/middle_africa/democratic_republic_of_the_congo'),
  (b'Denmark', 'europe/northern_europe/denmark'),
  (b'Djibouti', 'africa/eastern_africa/djibouti'),
  (b'Dominica', 'americas/caribbean/dominica'),
  (b'Dominican Republic', 'americas/caribbean/dominican_republic'),
  (b'Ecuador', 'americas/south_america/ecuador'),
  (b'Egypt', 'africa/northern_africa/egypt'),
  (b'El Salvador', 'americas/central_america/el_salvador'),
  (b'Equatorial Guinea', 'africa/middle_africa/equatorial_guinea'),
  (b'Eritrea', 'africa/eastern_africa/eritrea'),
  (b'Estonia', 'europe/northern_europe/estonia'),
  (b'Ethiopia', 'africa/eastern_africa/ethiopia'),
  (b'Faeroe Islands', 'europe/northern_europe/faeroe_islands'),
  (b'Falkland Islands (Malvinas)', 'americas/south_america/falkland_islands'),
  (b'Fiji', 'oceania/melanesia/fiji'),
  (b'Finland', 'europe/northern_europe/finland'),
  (b'France', 'europe/western_europe/france'),
  (b'French Guiana', 'americas/south_america/french_guiana'),
  (b'French Polynesia', 'oceania/polynesia/french_polynesia'),
  (b'Gabon', 'africa/middle_africa/gabon'),
  (b'Gambia', 'africa/western_africa/gambia'),
  (b'Georgia', 'asia/western_asia/georgia'),
  (b'Germany', 'europe/western_europe/germany'),
  (b'Ghana', 'africa/western_africa/ghana'),
  (b'Gibraltar', 'europe/southern_europe/gibraltar'),
  (b'Greece', 'europe/southern_europe/greece'),
  (b'Greenland', 'americas/northern_america/greenland'),
  (b'Grenada', 'americas/caribbean/grenada'),
  (b'Guadeloupe', 'americas/caribbean/guadeloupe'),
  (b'Guam', 'oceania/micronesia/guam'),
  (b'Guatemala', 'americas/central_america/guatemala'),
  (b'Guernsey', 'europe/northern_europe/guernsey'),
  (b'Guinea', 'africa/western_africa/guinea'),
  (b'Guinea-Bissau', 'africa/western_africa/guinea-bissau'),
  (b'Guyana', 'americas/south_america/guyana'),
  (b'Haiti', 'americas/caribbean/haiti'),
  (b'Holy See', 'europe/southern_europe/holy_see'),
  (b'Honduras', 'americas/central_america/honduras'),
  (b'Hong Kong Special Administrative Region of China', 'asia/eastern_asia/hong_kong'),
  (b'Hungary', 'europe/eastern_europe/hungary'),
  (b'Iceland', 'europe/northern_europe/iceland'),
  (b'India', 'asia/southern_asia/india'),
  (b'Indonesia', 'asia/south-eastern_asia/indonesia'),
  (b'Iran, Islamic Republic of', 'asia/southern_asia/iran'),
  (b'Iraq', 'asia/western_asia/iraq'),
  (b'Ireland', 'europe/northern_europe/ireland'),
  (b'Isle of Man', 'europe/northern_europe/isle_of_man'),
  (b'Israel', 'asia/western_asia/israel'),
  (b'Italy', 'europe/southern_europe/italy'),
  (b'Jamaica', 'americas/caribbean/jamaica'),
  (b'Japan', 'asia/eastern_asia/japan'),
  (b'Jersey', 'europe/northern_europe/jersey'),
  (b'Jordan', 'asia/western_asia/jordan'),
  (b'Kazakhstan', 'asia/central_asia/kazakhstan'),
  (b'Kenya', 'africa/eastern_africa/kenya'),
  (b'Kiribati', 'oceania/micronesia/kiribati'),
  (b'Kuwait', 'asia/western_asia/kuwait'),
  (b'Kyrgyzstan', 'asia/central_asia/kyrgyzstan'),
  (b"Lao People's Democratic Republic", 'asia/south-eastern_asia/lao_peoples_democratic_republic'),
  (b'Latvia', 'europe/northern_europe/latvia'),
  (b'Lebanon', 'asia/western_asia/lebanon'),
  (b'Lesotho', 'africa/southern_africa/lesotho'),
  (b'Liberia', 'africa/western_africa/liberia'),
  (b'Libyan Arab Jamahiriya', 'africa/northern_africa/libyan_arab_jamahiriya'),
  (b'Liechtenstein', 'europe/western_europe/liechtenstein'),
  (b'Lithuania', 'europe/northern_europe/lithuania'),
  (b'Luxembourg', 'europe/western_europe/luxembourg'),
  (b'Macao Special Administrative Region of China', 'asia/eastern_asia/macao'),
  (b'Madagascar', 'africa/eastern_africa/madagascar'),
  (b'Malawi', 'africa/eastern_africa/malawi'),
  (b'Malaysia', 'asia/south-eastern_asia/malaysia'),
  (b'Maldives', 'asia/southern_asia/maldives'),
  (b'Mali', 'africa/western_africa/mali'),
  (b'Malta', 'europe/southern_europe/malta'),
  (b'Marshall Islands', 'oceania/micronesia/marshall_islands'),
  (b'Martinique', 'americas/caribbean/martinique'),
  (b'Mauritania', 'africa/western_africa/mauritania'),
  (b'Mauritius', 'africa/eastern_africa/mauritius'),
  (b'Mayotte', 'africa/eastern_africa/mayotte'),
  (b'Mexico', 'americas/central_america/mexico'),
  (b'Micronesia, Federated States of', 'oceania/micronesia/federated_states_of_micronesia'),
  (b'Monaco', 'europe/western_europe/monaco'),
  (b'Mongolia', 'asia/eastern_asia/mongolia'),
  (b'Montenegro', 'europe/southern_europe/montenegro'),
  (b'Montserrat', 'americas/caribbean/montserrat'),
  (b'Morocco', 'africa/northern_africa/morocco'),
  (b'Mozambique', 'africa/eastern_africa/mozambique'),
  (b'Myanmar', 'asia/south-eastern_asia/myanmar'),
  (b'Namibia', 'africa/southern_africa/namibia'),
  (b'Nauru', 'oceania/micronesia/nauru'),
  (b'Nepal', 'asia/southern_asia/nepal'),
  (b'Netherlands', 'europe/western_europe/netherlands'),
  (b'Netherlands Antilles', 'americas/caribbean/netherlands_antilles'),
  (b'New Caledonia', 'oceania/melanesia/new_caledonia'),
  (b'New Zealand', 'oceania/australia/new_zealand'),
  (b'Nicaragua', 'americas/central_america/nicaragua'),
  (b'Niger', 'africa/western_africa/niger'),
  (b'Nigeria', 'africa/western_africa/nigeria'),
  (b'Niue', 'oceania/polynesia/niue'),
  (b'Norfolk Island', 'oceania/australia/norfolk_island'),
  (b'Northern Mariana Islands', 'oceania/micronesia/northern_mariana_islands'),
  (b'Norway', 'europe/northern_europe/norway'),
  (b'Occupied Palestinian Territory', 'asia/western_asia/occupied_palestinian_territory'),
  (b'Oman', 'asia/western_asia/oman'),
  (b'Pakistan', 'asia/southern_asia/pakistan'),
  (b'Palau', 'oceania/micronesia/palau'),
  (b'Panama', 'americas/central_america/panama'),
  (b'Papua New Guinea', 'oceania/melanesia/papua_new_guinea'),
  (b'Paraguay', 'americas/south_america/paraguay'),
  (b'Peru', 'americas/south_america/peru'),
  (b'Philippines', 'asia/south-eastern_asia/philippines'),
  (b'Pitcairn', 'oceania/polynesia/pitcairn'),
  (b'Poland', 'europe/eastern_europe/poland'),
  (b'Portugal', 'europe/southern_europe/portugal'),
  (b'Puerto Rico', 'americas/caribbean/puerto_rico'),
  (b'Qatar', 'asia/western_asia/qatar'),
  (b'Republic of Korea', 'asia/eastern_asia/republic_of_korea'),
  (b'Republic of Moldova', 'europe/eastern_europe/republic_of_moldova'),
  (b'Romania', 'europe/eastern_europe/romania'),
  (b'Russian Federation', 'europe/eastern_europe/russian_federation'),
  (b'Rwanda', 'africa/eastern_africa/rwanda'),
  (b'R\xc3\xa9union', 'africa/eastern_africa/reunion'),
  (b'Saint Helena', 'africa/western_africa/saint_helena'),
  (b'Saint Kitts and Nevis', 'americas/caribbean/saint_kitts_and_nevis'),
  (b'Saint Lucia', 'americas/caribbean/saint_lucia'),
  (b'Saint Martin (French part)', 'americas/caribbean/saint_martin'),
  (b'Saint Pierre and Miquelon', 'americas/northern_america/saint_pierre_and_miquelon'),
  (b'Saint Vincent and the Grenadines', 'americas/caribbean/saint_vincent_and_the_grenadines'),
  (b'Saint-Barth\xc3\xa9lemy', 'americas/caribbean/saint-barthelemy'),
  (b'Samoa', 'oceania/polynesia/samoa'),
  (b'San Marino', 'europe/southern_europe/san_marino'),
  (b'Sao Tome and Principe', 'africa/middle_africa/sao_tome_and_principe'),
  (b'Saudi Arabia', 'asia/western_asia/saudi_arabia'),
  (b'Senegal', 'africa/western_africa/senegal'),
  (b'Serbia', 'europe/southern_europe/serbia'),
  (b'Seychelles', 'africa/eastern_africa/seychelles'),
  (b'Sierra Leone', 'africa/western_africa/sierra_leone'),
  (b'Singapore', 'asia/south-eastern_asia/singapore'),
  (b'Slovakia', 'europe/eastern_europe/slovakia'),
  (b'Slovenia', 'europe/southern_europe/slovenia'),
  (b'Solomon Islands', 'oceania/melanesia/solomon_islands'),
  (b'Somalia', 'africa/eastern_africa/somalia'),
  (b'South Africa', 'africa/southern_africa/south_africa'),
  (b'Spain', 'europe/southern_europe/spain'),
  (b'Sri Lanka', 'asia/southern_asia/sri_lanka'),
  (b'Sudan', 'africa/northern_africa/sudan'),
  (b'Suriname', 'americas/south_america/suriname'),
  (b'Svalbard and Jan Mayen Islands', 'europe/northern_europe/svalbard_and_jan_mayen_islands'),
  (b'Swaziland', 'africa/southern_africa/swaziland'),
  (b'Sweden', 'europe/northern_europe/sweden'),
  (b'Switzerland', 'europe/western_europe/switzerland'),
  (b'Syrian Arab Republic', 'asia/western_asia/syrian_arab_republic'),
  (b'Tajikistan', 'asia/central_asia/tajikistan'),
  (b'Thailand', 'asia/south-eastern_asia/thailand'),
  (b'The former Yugoslav Republic of Macedonia', 'europe/southern_europe/macedonia'),
  (b'Timor-Leste', 'asia/south-eastern_asia/timor-leste'),
  (b'Togo', 'africa/western_africa/togo'),
  (b'Tokelau', 'oceania/polynesia/tokelau'),
  (b'Tonga', 'oceania/polynesia/tonga'),
  (b'Trinidad and Tobago', 'americas/caribbean/trinidad_and_tobago'),
  (b'Tunisia', 'africa/northern_africa/tunisia'),
  (b'Turkey', 'asia/western_asia/turkey'),
  (b'Turkmenistan', 'asia/central_asia/turkmenistan'),
  (b'Turks and Caicos Islands', 'americas/caribbean/turks_and_caicos_islands'),
  (b'Tuvalu', 'oceania/polynesia/tuvalu'),
  (b'Uganda', 'africa/eastern_africa/uganda'),
  (b'Ukraine', 'europe/eastern_europe/ukraine'),
  (b'United Arab Emirates', 'asia/western_asia/united_arab_emirates'),
  (b'United Kingdom of Great Britain and Northern Ireland', 'europe/northern_europe/united_kingdom'),
  (b'United Republic of Tanzania', 'africa/eastern_africa/united_republic_of_tanzania'),
  (b'United States Virgin Islands', 'americas/caribbean/united_states_virgin_islands'),
  (b'United States of America', 'americas/northern_america/united_states_of_america'),
  (b'Uruguay', 'americas/south_america/uruguay'),
  (b'Uzbekistan', 'asia/central_asia/uzbekistan'),
  (b'Vanuatu', 'oceania/melanesia/vanuatu'),
  (b'Venezuela (Bolivarian Republic of)', 'americas/south_america/venezuela'),
  (b'Viet Nam', 'asia/south-eastern_asia/viet_nam'),
  (b'Wallis and Futuna Islands', 'oceania/polynesia/wallis_and_futuna_islands'),
  (b'Western Sahara', 'africa/northern_africa/western_sahara'),
  (b'Yemen', 'asia/western_asia/yemen'),
  (b'Zambia', 'africa/eastern_africa/zambia'),
  (b'Zimbabwe', 'africa/eastern_africa/zimbabwe'),
  (b'\xc3\x85land Islands', 'europe/northern_europe/aland_islands'),
]

return [['', '']] + [[str(translateString(title.decode('utf-8'))), relative_url] for (title, relative_url) in region_item_list]
