base = context.absolute_url() + '/../..'
return """<?xml version="1.0" encoding="UTF-8"?>
<!-- OPML generated by SlapOS -->
<opml version="1.1">
        <head>
                <title>TEST Hosting Subscription</title>
                <dateCreated>Fri, 17 Jan 2020 12:16:59 +0000</dateCreated>
                <dateModified>Fri, 17 Jan 2020 12:16:59 +0000</dateModified>
        </head>
        <body>
          <outline text="Monitoring RSS Feed list">
<outline text="rootInstance" title="rootInstance" type="rss" version="RSS" htmlUrl="%(base)s/rootInstance/public/feed" xmlUrl="%(base)s/rootInstance/public/feed" url="%(base)s/rootInstance/share/private/" />
<outline text="subInstance-1" title="subInstance-1" type="rss" version="RSS" htmlUrl="%(base)s/subInstance-1/public/feed" xmlUrl="%(base)s/subInstance-1/public/feed" url="%(base)s/subInstance-1/share/private/" />
<outline text="subInstance-2" title="subInstance-2" type="rss" version="RSS" htmlUrl="%(base)s/subInstance-2/public/feed" xmlUrl="%(base)s/subInstance-2/public/feed" url="%(base)s/subInstance-2/share/private/" />      </outline>
  </body>
</opml>""" % {'base': base}
