url_list = [
  'plotly_strict_v3.0.0.js',
  'plotly_strict_v3.0.0.css',
  'gadget_ors_rms_rx.js',
  'gadget_ors_rms_rx.html',
  'gadget_ors_failure_rrc_security_mode.js',
  'gadget_ors_failure_rrc_security_mode.html',
  'gadget_ors_unsuccessful_rrc_connection_attempt.js',
  'gadget_ors_unsuccessful_rrc_connection_attempt.html',
  'gadget_ors_rrc_paging.js',
  'gadget_ors_rrc_paging.html',
  'gadget_ors_rrc_connection_request.js',
  'gadget_ors_rrc_connection_request.html',
  'gadget_ors_ue_count.js',
  'gadget_ors_ue_count.html',
  'gadget_ors_rrc_ue_count.js',
  'gadget_ors_rrc_ue_count.html',
  'gadget_ors_e_utran_ip_throughput_kpi.html',
  'gadget_ors_e_utran_ip_throughput_kpi.js',
  'gadget_ors_e_rab_accessibility_kpi.html',
  'gadget_ors_e_rab_accessibility_kpi.js',
  'gadget_ors_kpi.css',
]

return url_list
