base = context.portal_tests.web_monitoring_ui_zuite.MonitorBackend_getBaseUrl()
# normalize
path = path.strip('/')
# normalize share
path = path.replace('share/', '')
value = {
  'rootInstance/public/feeds': """<?xml version="1.0" encoding="UTF-8"?>
<!-- OPML generated by SlapOS -->
<opml version="1.1">
        <head>
                <title>TEST Hosting Subscription</title>
                <dateCreated>Fri, 17 Jan 2020 12:16:59 +0000</dateCreated>
                <dateModified>Fri, 17 Jan 2020 12:16:59 +0000</dateModified>
        </head>
        <body>
          <outline text="Monitoring RSS Feed list">
<outline text="rootInstance" title="rootInstance" type="rss" version="RSS" htmlUrl="%(base)s/rootInstance/public/feed" xmlUrl="%(base)s/rootInstance/public/feed" url="%(base)s/rootInstance/share/private/" />
<outline text="subInstance-1" title="subInstance-1" type="rss" version="RSS" htmlUrl="%(base)s/subInstance-1/public/feed" xmlUrl="%(base)s/subInstance-1/public/feed" url="%(base)s/subInstance-1/share/private/" />
<outline text="subInstance-2" title="subInstance-2" type="rss" version="RSS" htmlUrl="%(base)s/subInstance-2/public/feed" xmlUrl="%(base)s/subInstance-2/public/feed" url="%(base)s/subInstance-2/share/private/" />      </outline>
  </body>
</opml>""",
  'rootInstance/public/feed': """<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>rootInstance</title>
    <link>%(base)s/rootInstance/public/feed</link>
    <description>TEST Hosting Subscription</description>
    <lastBuildDate>Fri, 17 Jan 2020 12:16:59 +0000</lastBuildDate>
    <docs>%(base)s/gc//blogs.law.harvard.edu/tech/rss</docs>
    <item>
      <title>test_promise_3</title>
      <link>%(base)s/rootInstance/share/private/</link>
      <description>description of test_promise_3</description>
      <category>OK</category>
      <comments />
      <guid isPermaLink="false">VU5LTk9XTiwgc2xhcHJ1bm5l1579263419==</guid>
      <pubDate>Fri, 17 Jan 2020 12:16:59 +0000</pubDate>
      <source url="%(base)s/rootInstance/share/public/">test_promise_3</source>
    </item>
    <item>
      <title>test_promise_0</title>
      <link>%(base)s/rootInstance/share/private/</link>
      <description>description of test_promise_0</description>
      <category>OK</category>
      <comments />
      <guid isPermaLink="false">VU5LTk9XTiwgc2xhcHJ1bm5l1579263419==</guid>
      <pubDate>Fri, 17 Jan 2020 12:16:59 +0000</pubDate>
      <source url="%(base)s/rootInstance/share/public/">test_promise_0</source>
    </item>
    <item>
      <title>test_promise_2</title>
      <link>%(base)s/rootInstance/share/private/</link>
      <description>description of test_promise_2</description>
      <category>OK</category>
      <comments />
      <guid isPermaLink="false">VU5LTk9XTiwgc2xhcHJ1bm5l1579263419==</guid>
      <pubDate>Fri, 17 Jan 2020 12:16:59 +0000</pubDate>
      <source url="%(base)s/rootInstance/share/public/">test_promise_2</source>
    </item>
    <item>
      <title>test_promise_1</title>
      <link>%(base)s/rootInstance/share/private/</link>
      <description>description of test_promise_1</description>
      <category>OK</category>
      <comments />
      <guid isPermaLink="false">VU5LTk9XTiwgc2xhcHJ1bm5l1579263419==</guid>
      <pubDate>Fri, 17 Jan 2020 12:16:59 +0000</pubDate>
      <source url="%(base)s/rootInstance/share/public/">test_promise_1</source>
    </item>
    <item>
      <title>test_promise_4</title>
      <link>%(base)s/rootInstance/share/private/</link>
      <description>description of test_promise_4</description>
      <category>OK</category>
      <comments />
      <guid isPermaLink="false">VU5LTk9XTiwgc2xhcHJ1bm5l1579263419==</guid>
      <pubDate>Fri, 17 Jan 2020 12:16:59 +0000</pubDate>
      <source url="%(base)s/rootInstance/share/public/">test_promise_4</source>
    </item>
  </channel>
</rss>""",
  'rootInstance/public/test_promise_0.json': """{"status": "OK", "change-time": 1579263419.246462, "instance": "rootInstance", "hosting_subscription": "TEST Hosting Subscription", "title": "test_promise_0", "_links": {"monitor": {"href": "%(base)s/rootInstance/share/private/"}}, "message": "Test Promise ran with status OK", "start-date": "2020-01-17 13:16:59", "type": "status"}""",
  'rootInstance/public/test_promise_1.json': """{"status": "OK", "change-time": 1579263419.246462, "instance": "rootInstance", "hosting_subscription": "TEST Hosting Subscription", "title": "test_promise_1", "_links": {"monitor": {"href": "%(base)s/rootInstance/share/private/"}}, "message": "Test Promise ran with status OK", "start-date": "2020-01-17 13:16:59", "type": "status"}""",
  'rootInstance/public/test_promise_2.json': """{"status": "OK", "change-time": 1579263419.246462, "instance": "rootInstance", "hosting_subscription": "TEST Hosting Subscription", "title": "test_promise_2", "_links": {"monitor": {"href": "%(base)s/rootInstance/share/private/"}}, "message": "Test Promise ran with status OK", "start-date": "2020-01-17 13:16:59", "type": "status"}""",
  'rootInstance/public/test_promise_3.json': """{"status": "OK", "change-time": 1579263419.246462, "instance": "rootInstance", "hosting_subscription": "TEST Hosting Subscription", "title": "test_promise_3", "_links": {"monitor": {"href": "%(base)s/rootInstance/share/private/"}}, "message": "Test Promise ran with status OK", "start-date": "2020-01-17 13:16:59", "type": "status"}""",
  'rootInstance/public/test_promise_4.json': """{"status": "OK", "change-time": 1579263419.246462, "instance": "rootInstance", "hosting_subscription": "TEST Hosting Subscription", "title": "test_promise_4", "_links": {"monitor": {"href": "%(base)s/rootInstance/share/private/"}}, "message": "Test Promise ran with status OK", "start-date": "2020-01-17 13:16:59", "type": "status"}""",
  'rootInstance/private/_document_list': """monitor.global""",
  'monitor.global.json': """{"status": "OK", "_links": {"rss_url": {"href": "%(base)s/rootInstance/public/feed"}, "public_url": {"href": "%(base)s/rootInstance/share/public/"}, "private_url": {"href": "%(base)s/rootInstance/share/private/"}}, "state": {"warning": 0, "success": 3, "error": 0}, "_embedded": {"instance": {"partition": "slappart1", "ipv6": "2001:67c:1254:e:c4::c748", "computer": "slaprunner", "ipv4": "10.0.165.37", "software-release": "http://xxx.yyy.zz/asoftware/software.cfg", "software-type": "pull-backup"}}, "parameters": [{"key": "", "value": "some parameter", "title": "demo"}], "title": "rootInstance", "date": "2020-01-17 13:16:59", "type": "global", "hosting-title": "TEST Hosting Subscription", "data": {"process_state": "monitor_process_resource.status", "io_resource": "monitor_resource_io.data", "state": "monitor_state.data", "memory_resource": "monitor_resource_memory.data", "process_resource": "monitor_resource_process.data", "monitor_process_state": "monitor_resource.status"}}""",
  'subInstance-1/public/feed': """<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>subInstance-1</title>
    <link>%(base)s/subInstance-1/public/feed</link>
    <description>TEST Hosting Subscription</description>
    <lastBuildDate>Fri, 17 Jan 2020 12:16:59 +0000</lastBuildDate>
    <docs>%(base)s/gc//blogs.law.harvard.edu/tech/rss</docs>
    <item>
      <title>test_promise_3</title>
      <link>>%(base)s/subInstance-1/share/private/</link>
      <description>description of test_promise_3</description>
      <category>OK</category>
      <comments />
      <guid isPermaLink="false">VU5LTk9XTiwgc2xhcHJ1bm5l1579263419==</guid>
      <pubDate>Fri, 17 Jan 2020 12:16:59 +0000</pubDate>
      <source url=">%(base)s/subInstance-1/share/public/">test_promise_3</source>
    </item>
    <item>
      <title>test_promise_0</title>
      <link>>%(base)s/subInstance-1/share/private/</link>
      <description>description of test_promise_0</description>
      <category>OK</category>
      <comments />
      <guid isPermaLink="false">VU5LTk9XTiwgc2xhcHJ1bm5l1579263419==</guid>
      <pubDate>Fri, 17 Jan 2020 12:16:59 +0000</pubDate>
      <source url=">%(base)s/subInstance-1/share/public/">test_promise_0</source>
    </item>
    <item>
      <title>test_promise_2</title>
      <link>>%(base)s/subInstance-1/share/private/</link>
      <description>description of test_promise_2</description>
      <category>OK</category>
      <comments />
      <guid isPermaLink="false">VU5LTk9XTiwgc2xhcHJ1bm5l1579263419==</guid>
      <pubDate>Fri, 17 Jan 2020 12:16:59 +0000</pubDate>
      <source url=">%(base)s/subInstance-1/share/public/">test_promise_2</source>
    </item>
    <item>
      <title>test_promise_1</title>
      <link>>%(base)s/subInstance-1/share/private/</link>
      <description>description of test_promise_1</description>
      <category>OK</category>
      <comments />
      <guid isPermaLink="false">VU5LTk9XTiwgc2xhcHJ1bm5l1579263419==</guid>
      <pubDate>Fri, 17 Jan 2020 12:16:59 +0000</pubDate>
      <source url=">%(base)s/subInstance-1/share/public/">test_promise_1</source>
    </item>
  </channel>
</rss>""",
  'subInstance-1/private/_document_list': """monitor.global""",
  'subInstance-1/private/monitor.global.json': """{"status": "ERROR", "_links": {"rss_url": {"href": "%(base)s/subInstance-1/public/feed"}, "public_url": {"href": "%(base)s/subInstance-1/share/public/"}, "private_url": {"href": "%(base)s/subInstance-1/share/private/"}}, "state": {"warning": 0, "success": 3, "error": 0}, "_embedded": {"instance": {"partition": "slappart1", "ipv6": "2001:67c:1254:e:c4::c748", "computer": "slaprunner", "ipv4": "10.0.165.37", "software-release": "http://xxx.yyy.zz/asoftware/software.cfg", "software-type": "pull-backup"}}, "parameters": [{"key": "", "value": "some parameter", "title": "demo"}], "title": "subInstance-1", "date": "2020-01-17 13:16:59", "type": "global", "hosting-title": "TEST Hosting Subscription", "data": {"process_state": "monitor_process_resource.status", "io_resource": "monitor_resource_io.data", "state": "monitor_state.data", "memory_resource": "monitor_resource_memory.data", "process_resource": "monitor_resource_process.data", "monitor_process_state": "monitor_resource.status"}}""",
  'subInstance-1/public/test_promise_0.json': """{"status": "ERROR", "change-time": 1579263419.247024, "instance": "subInstance-1", "hosting_subscription": "TEST Hosting Subscription", "title": "test_promise_0", "_links": {"monitor": {"href": "%(base)s/subInstance-1/share/private/"}}, "message": "Test Promise ran with status ERROR", "start-date": "2020-01-17 13:16:59", "type": "status"}""",
  'subInstance-1/public/test_promise_1.json': """{"status": "ERROR", "change-time": 1579263419.247024, "instance": "subInstance-1", "hosting_subscription": "TEST Hosting Subscription", "title": "test_promise_1", "_links": {"monitor": {"href": "%(base)s/subInstance-1/share/private/"}}, "message": "Test Promise ran with status ERROR", "start-date": "2020-01-17 13:16:59", "type": "status"}""",
  'subInstance-1/public/test_promise_2.json': """{"status": "ERROR", "change-time": 1579263419.247024, "instance": "subInstance-1", "hosting_subscription": "TEST Hosting Subscription", "title": "test_promise_2", "_links": {"monitor": {"href": "%(base)s/subInstance-1/share/private/"}}, "message": "Test Promise ran with status ERROR", "start-date": "2020-01-17 13:16:59", "type": "status"}""",
  'subInstance-1/public/test_promise_3.json': """{"status": "ERROR", "change-time": 1579263419.247024, "instance": "subInstance-1", "hosting_subscription": "TEST Hosting Subscription", "title": "test_promise_3", "_links": {"monitor": {"href": "%(base)s/subInstance-1/share/private/"}}, "message": "Test Promise ran with status ERROR", "start-date": "2020-01-17 13:16:59", "type": "status"}""",
  'subInstance-2/public/feed': """<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>subInstance-2</title>
    <link>%(base)s/subInstance-2/public/feed</link>
    <description>TEST Hosting Subscription</description>
    <lastBuildDate>Fri, 17 Jan 2020 12:16:59 +0000</lastBuildDate>
    <docs>%(base)s/gc//blogs.law.harvard.edu/tech/rss</docs>
    <item>
      <title>test_promise_5</title>
      <link>%(base)s/subInstance-2/share/private/</link>
      <description>description of test_promise_5</description>
      <category>OK</category>
      <comments />
      <guid isPermaLink="false">VU5LTk9XTiwgc2xhcHJ1bm5l1579263419==</guid>
      <pubDate>Fri, 17 Jan 2020 12:16:59 +0000</pubDate>
      <source url="%(base)s/subInstance-2/share/public/">test_promise_5</source>
    </item>
    <item>
      <title>test_promise_3</title>
      <link>%(base)s/subInstance-2/share/private/</link>
      <description>description of test_promise_3</description>
      <category>OK</category>
      <comments />
      <guid isPermaLink="false">VU5LTk9XTiwgc2xhcHJ1bm5l1579263419==</guid>
      <pubDate>Fri, 17 Jan 2020 12:16:59 +0000</pubDate>
      <source url="%(base)s/subInstance-2/share/public/">test_promise_3</source>
    </item>
    <item>
      <title>test_promise_6</title>
      <link>%(base)s/subInstance-2/share/private/</link>
      <description>description of test_promise_6</description>
      <category>OK</category>
      <comments />
      <guid isPermaLink="false">VU5LTk9XTiwgc2xhcHJ1bm5l1579263419==</guid>
      <pubDate>Fri, 17 Jan 2020 12:16:59 +0000</pubDate>
      <source url="%(base)s/subInstance-2/share/public/">test_promise_6</source>
    </item>
    <item>
      <title>test_promise_0</title>
      <link>%(base)s/subInstance-2/share/private/</link>
      <description>description of test_promise_0</description>
      <category>OK</category>
      <comments />
      <guid isPermaLink="false">VU5LTk9XTiwgc2xhcHJ1bm5l1579263419==</guid>
      <pubDate>Fri, 17 Jan 2020 12:16:59 +0000</pubDate>
      <source url="%(base)s/subInstance-2/share/public/">test_promise_0</source>
    </item>
    <item>
      <title>test_promise_2</title>
      <link>%(base)s/subInstance-2/share/private/</link>
      <description>description of test_promise_2</description>
      <category>OK</category>
      <comments />
      <guid isPermaLink="false">VU5LTk9XTiwgc2xhcHJ1bm5l1579263419==</guid>
      <pubDate>Fri, 17 Jan 2020 12:16:59 +0000</pubDate>
      <source url="%(base)s/subInstance-2/share/public/">test_promise_2</source>
    </item>
    <item>
      <title>test_promise_1</title>
      <link>%(base)s/subInstance-2/share/private/</link>
      <description>description of test_promise_1</description>
      <category>OK</category>
      <comments />
      <guid isPermaLink="false">VU5LTk9XTiwgc2xhcHJ1bm5l1579263419==</guid>
      <pubDate>Fri, 17 Jan 2020 12:16:59 +0000</pubDate>
      <source url="%(base)s/subInstance-2/share/public/">test_promise_1</source>
    </item>
    <item>
      <title>test_promise_4</title>
      <link>%(base)s/subInstance-2/share/private/</link>
      <description>description of test_promise_4</description>
      <category>OK</category>
      <comments />
      <guid isPermaLink="false">VU5LTk9XTiwgc2xhcHJ1bm5l1579263419==</guid>
      <pubDate>Fri, 17 Jan 2020 12:16:59 +0000</pubDate>
      <source url="%(base)s/subInstance-2/share/public/">test_promise_4</source>
    </item>
  </channel>
</rss>""",
  'subInstance-2/public/test_promise_0.json': """{"status": "OK", "change-time": 1579263419.247408, "instance": "subInstance-2", "hosting_subscription": "TEST Hosting Subscription", "title": "test_promise_0", "_links": {"monitor": {"href": "%(base)s/subInstance-2/share/private/"}}, "message": "Test Promise ran with status OK", "start-date": "2020-01-17 13:16:59", "type": "status"}""",
  'subInstance-2/public/test_promise_1.json': """{"status": "OK", "change-time": 1579263419.247408, "instance": "subInstance-2", "hosting_subscription": "TEST Hosting Subscription", "title": "test_promise_1", "_links": {"monitor": {"href": "%(base)s/subInstance-2/share/private/"}}, "message": "Test Promise ran with status OK", "start-date": "2020-01-17 13:16:59", "type": "status"}""",
  'subInstance-2/public/test_promise_2.json': """{"status": "OK", "change-time": 1579263419.247408, "instance": "subInstance-2", "hosting_subscription": "TEST Hosting Subscription", "title": "test_promise_2", "_links": {"monitor": {"href": "%(base)s/subInstance-2/share/private/"}}, "message": "Test Promise ran with status OK", "start-date": "2020-01-17 13:16:59", "type": "status"}""",
  'subInstance-2/public/test_promise_3.json': """{"status": "OK", "change-time": 1579263419.247408, "instance": "subInstance-2", "hosting_subscription": "TEST Hosting Subscription", "title": "test_promise_3", "_links": {"monitor": {"href": "%(base)s/subInstance-2/share/private/"}}, "message": "Test Promise ran with status OK", "start-date": "2020-01-17 13:16:59", "type": "status"}""",
  'subInstance-2/public/test_promise_4.json': """{"status": "OK", "change-time": 1579263419.247408, "instance": "subInstance-2", "hosting_subscription": "TEST Hosting Subscription", "title": "test_promise_4", "_links": {"monitor": {"href": "%(base)s/subInstance-2/share/private/"}}, "message": "Test Promise ran with status OK", "start-date": "2020-01-17 13:16:59", "type": "status"}""",
  'subInstance-2/public/test_promise_5.json': """{"status": "OK", "change-time": 1579263419.247408, "instance": "subInstance-2", "hosting_subscription": "TEST Hosting Subscription", "title": "test_promise_5", "_links": {"monitor": {"href": "%(base)s/subInstance-2/share/private/"}}, "message": "Test Promise ran with status OK", "start-date": "2020-01-17 13:16:59", "type": "status"}""",
  'subInstance-2/public/test_promise_6.json': """{"status": "OK", "change-time": 1579263419.247408, "instance": "subInstance-2", "hosting_subscription": "TEST Hosting Subscription", "title": "test_promise_6", "_links": {"monitor": {"href": "%(base)s/subInstance-2/share/private/"}}, "message": "Test Promise ran with status OK", "start-date": "2020-01-17 13:16:59", "type": "status"}""",
  'subInstance-2/private/_document_list': """monitor.global""",
  'subInstance-2/private/monitor.global.json': """{"status": "OK", "_links": {"rss_url": {"href": "%(base)s/subInstance-2/public/feed"}, "public_url": {"href": "%(base)s/subInstance-2/share/public/"}, "private_url": {"href": "%(base)s/subInstance-2/share/private/"}}, "state": {"warning": 0, "success": 3, "error": 0}, "_embedded": {"instance": {"partition": "slappart1", "ipv6": "2001:67c:1254:e:c4::c748", "computer": "slaprunner", "ipv4": "10.0.165.37", "software-release": "http://xxx.yyy.zz/asoftware/software.cfg", "software-type": "pull-backup"}}, "parameters": [{"key": "", "value": "some parameter", "title": "demo"}], "title": "subInstance-2", "date": "2020-01-17 13:16:59", "type": "global", "hosting-title": "TEST Hosting Subscription", "data": {"process_state": "monitor_process_resource.status", "io_resource": "monitor_resource_io.data", "state": "monitor_state.data", "memory_resource": "monitor_resource_memory.data", "process_resource": "monitor_resource_process.data", "monitor_process_state": "monitor_resource.status"}}""",
}.get(path, None)

if 'json' in path:
  context.REQUEST.response.setHeader('Content-Type', 'application/json')
  if value is None:
    value = '{}'
if value is not None:
  return value % {'base': base}
else:
  script.log(path)
