DROP TABLE IF EXISTS worklist_cache
<dtml-var sql_delimiter>
CREATE TABLE `worklist_cache` (
  `count` INT UNSIGNED NOT NULL,
  `owner` VARCHAR(255) binary DEFAULT '',
  `viewable_owner` VARCHAR(255) binary NOT NULL DEFAULT '',
  `security_uid` INT UNSIGNED NOT NULL,
  `alternate_security_uid` INT UNSIGNED,
  `other_security_uid` INT UNSIGNED,
  `portal_type` VARCHAR(255) NOT NULL,
  `validation_state` VARCHAR(255) NULL,
  `simulation_state` VARCHAR(255) NULL,
  `parent_uid` BIGINT UNSIGNED default '0',
  `title` varchar(255) default '',
  `opportunity_state` varchar(255) default '',
  `causality_state` varchar(255) default '',
  `invoice_state` varchar(255) default '',
  `payment_state` varchar(255) default '',
  `event_state` varchar(255) default '',
  `immobilisation_state` varchar(255) default '',
  `reference` varchar(255) binary default '',
  `grouping_reference` varchar(255) default '',
  `source_reference` varchar(255) default '',
  `destination_reference` varchar(255) default '',
  `string_index` varchar(255),
  `int_index` INT,
  `float_index` real,
  `has_cell_content` bool,
  `creation_date` datetime,
  `modification_date` datetime,
  KEY `portal_simulation_security` (`portal_type`, `simulation_state`, `security_uid`),
  KEY `portal_simulation_owner` (`portal_type`, `simulation_state`, `viewable_owner`),
  KEY `portal_validation_security` (`portal_type`, `validation_state`, `security_uid`),
  KEY `portal_validation_owner` (`portal_type`, `validation_state`, `viewable_owner`)
) ENGINE=InnoDB