portal = context.getPortalObject()
type_definition = context.getTypeInfo()
membership_criterion_base_category_set = set([]) #set(context.getMembershipCriterionBaseCategoryList())
multimembership_criterion_base_category_set = set([]) #set(context.getMultimembershipCriterionBaseCategoryList())
multimembership_criterion_base_category_set.update(membership_criterion_base_category_set)
multimembership_criterion_base_category_set.add("publication_section")
membership_criterion_base_category_list = []
multimembership_criterion_base_category_list = list(multimembership_criterion_base_category_set)
membership_criterion_category_list = context.getMembershipCriterionCategoryList()

context.setTitle("Forum")
context.setDefaultPageDisplayed(True)
context.setCustomRenderMethodId("WebSection_viewDiscussionThreadForm")
context.setCriterionProperty("portal_type")
context.setEmptyCriterionValid(True)
context.setMembershipCriterionBaseCategory(membership_criterion_base_category_list)
context.setMultimembershipCriterionBaseCategory(multimembership_criterion_base_category_list)
context.setMembershipCriterionCategory(membership_criterion_category_list + ["publication_section/forum"])
context.setCriterion("portal_type", "Discussion Thread")
