url_list = [
  #image app specific
  "gadget_officejs_image_editor.configuration",
  "gadget_officejs_image_editor_router.html",
  "gadget_officejs_jio_image_view.html",
  "gadget_officejs_jio_image_view.js",
  "gadget_officejs_image_editor.json",
  "image_editor_app_logo.svg",

  #image editor
  "minipaint.gadget.html",
  "minipaint.gadget.js",
  "miniPaint/config.js",
  "miniPaint/img/right.png",
  "miniPaint/img/logo.png",
  "miniPaint/img/colorwheel.png",
  "miniPaint/img/favicon.png",
  "miniPaint/img/preview.jpg",
  "miniPaint/img/sprites.png",
  "miniPaint/js/draw_tools.js",
  "miniPaint/js/edit.js",
  "miniPaint/js/effects.js",
  "miniPaint/js/elements.js",
  "miniPaint/js/events.js",
  "miniPaint/js/file.js",
  "miniPaint/js/gui.js",
  "miniPaint/js/help.js",
  "miniPaint/js/image.js",
  "miniPaint/js/layers.js",
  "miniPaint/js/main.js",
  "miniPaint/js/tools.js",
  "miniPaint/languages/de.js",
  "miniPaint/languages/empty.js",
  "miniPaint/languages/es.js",
  "miniPaint/languages/fr.js",
  "miniPaint/languages/it.js",
  "miniPaint/languages/ja.js",
  "miniPaint/languages/ko.js",
  "miniPaint/languages/lt.js",
  "miniPaint/languages/pt.js",
  "miniPaint/languages/ru.js",
  "miniPaint/languages/tr.js",
  "miniPaint/languages/zh.js",
  "miniPaint/libs/helpers.js",
  "miniPaint/libs/popup.js",
  "miniPaint/libs/sift.js",
  "miniPaint/libs/vintage.js",
  "miniPaint/styles/styles.css",
  "miniPaint/vendor/exif/exif.js",
  "miniPaint/vendor/exif/exif.min.js",
  "miniPaint/vendor/file-saver/FileSaver.min.js",
  "miniPaint/vendor/file-saver/canvas-toBlob.js",
  "miniPaint/vendor/glfx/glfx.js",
  "miniPaint/vendor/harmony/harmony.js",
  "miniPaint/vendor/harmony/harmony.min.js",
  "miniPaint/vendor/hermite-resize/hermite.js",
  "miniPaint/vendor/hqx/hqx.js",
  "miniPaint/vendor/hqx/hqx.min.js",
  "miniPaint/vendor/imagefilters/imagefilters.js",
  "miniPaint/vendor/imagefilters/imagefilters.min.js",
  "miniPaint/vendor/jquery/jquery-migrate.js",
  "miniPaint/vendor/jquery/jquery.js",
  "miniPaint/vendor/menu/menu.js",
  "miniPaint/vendor/menu/menu.min.js",
  "miniPaint/vendor/translate/jquery.translate.js",
  "miniPaint/vendor/translate/jquery.translate.min.js",

  #app_configuration_resources
  #CONFIGURATION ELEMENTS generated on Wed Apr 01 14:45:53 2020. Same as in configuration manifest
  "hateoas_appcache/definition_view/cG9ydGFsX3R5cGVzL0ltYWdl",
  "hateoas_appcache/definition_view/cG9ydGFsX3R5cGVzL0ltYWdlL2ltYWdlX2VkaXRvcl92aWV3",
  "hateoas_appcache/definition_view/cG9ydGFsX3NraW5zL2VycDVfaW1hZ2VfZWRpdG9yL0ltYWdlX3ZpZXdBc0ppb0ZvckltYWdlRWRpdG9y",
  "hateoas_appcache/definition_view/cG9ydGFsX3R5cGVzL0ltYWdlIE1vZHVsZQ==",
  "hateoas_appcache/definition_view/cG9ydGFsX3R5cGVzL0ltYWdlIE1vZHVsZS9pbWFnZV9lZGl0b3Jfdmlldw==",
  "hateoas_appcache/definition_view/cG9ydGFsX3NraW5zL2VycDVfaW1hZ2VfZWRpdG9yL0ltYWdlTW9kdWxlX3ZpZXdJbWFnZUxpc3RBc0ppb0ZvckltYWdlRWRpdG9y",
  #/app_configuration_resources
]

return url_list
