#!/bin/bash
while true; do
wget -O /tmp/zope_distribute.out http://jp:jp@localhost:9673/coramy/portal_activities/distribute?node_count:int=1
wget -O /tmp/zope_tic.out http://jp:jp@localhost:9673/coramy/portal_activities/tic?processing_node:int=1
sleep 5
done
