url_list = [
  "gadget_officejs_drone_capture_flag.json",
  "drone_flag.png",
  "gadget_erp5_page_drone_capture_flag_logic.js",
  "gadget_erp5_page_drone_capture_flag_script_page.html",
  "gadget_erp5_page_drone_capture_flag_script_page.js",
  "gadget_erp5_panel_drone_capture_flag.html",
  "gadget_erp5_panel_drone_capture_flag.js",
  "gadget_erp5_page_drone_capture_flag_fixedwingdrone.js",
  "gadget_erp5_page_drone_capture_flag_enemydrone.js",
  "gadget_erp5_page_drone_capture_flag_api_page.html",
  "gadget_erp5_page_drone_capture_flag_api_page.js",
  "gadget_erp5_page_drone_capture_flag_api_page.css",
  "assets/map/terrain.jpg",
  "assets/map/map.babylon",
  "assets/drone/drone.babylon",
  "assets/drone/drone_bleu.jpg",
  "assets/drone/drone_bleu_old.jpg",
  "assets/drone/drone_rouge.jpg",
  "assets/drone/drone_rouge_old.jpg",
  "assets/skybox/sky_nx.jpg",
  "assets/skybox/sky_ny.jpg",
  "assets/skybox/sky_nz.jpg",
  "assets/skybox/sky_px.jpg",
  "assets/skybox/sky_py.jpg",
  "assets/skybox/sky_pz.jpg",
  "libraries/seedrandom.min.js"
]

return url_list
