context.Base_createUITestLanguages(['zh'])
param_dict = [
  { 'message': 'History', 'translation': 'lishi', 'language': 'zh'},
  { 'message': 'Cut', 'translation': 'jianque', 'language': 'zh'},
  { 'message': 'Proceed', 'translation': 'jixu', 'language': 'zh'},
  { 'message': 'Title', 'translation': 'biaoti', 'language': 'zh'},
  { 'message': 'Equals To', 'translation': 'dengyu', 'language': 'zh'},
  { 'message': 'Contain', 'translation': 'baohang', 'language': 'zh'},
  { 'message': 'Search', 'translation': 'soushuo', 'language': 'zh'},
  { 'message': 'Next', 'translation': 'houyige', 'language': 'zh'},
  { 'message': 'Add', 'translation': 'zhenjia', 'language': 'zh'},
  { 'message': 'Loading', 'translation': 'jiazhaizhong', 'language': 'zh'},
  { 'message': 'Actions', 'translation': 'caozhuo', 'language': 'zh'},
  { 'message': 'Explore the Search Result List', 'translation': 'liulangjieguo', 'language': 'zh'},
  { 'message': 'Save', 'translation': 'baochun', 'language': 'zh'},
  { 'message': 'Type', 'translation': 'leixing', 'language': 'zh'},
  { 'message': 'No records', 'translation': 'meiyoujilu', 'language': 'zh'},
  { 'message': 'Sort', 'translation': 'paixu', 'language': 'zh'},
  { 'message': 'Create New', 'translation': 'tianjia', 'language': 'zh'},
  { 'message': 'Description', 'translation': 'miaoshu', 'language': 'zh'},
  { 'message': 'Greater Than', 'translation': 'dayu', 'language': 'zh'},
  { 'message': 'Confirm', 'translation': 'queren', 'language': 'zh'},
  { 'message': 'Editable', 'translation': 'bianxue', 'language': 'zh'},
  { 'message': 'Less Than', 'translation': 'xiaoyu', 'language': 'zh'},
  { 'message': 'Records', 'translation': 'jilu', 'language': 'zh'},
  { 'message': 'All criterions (AND)', 'translation': 'fuheshuoyou', 'language': 'zh'},
  { 'message': 'Logout', 'translation': 'tuichu', 'language': 'zh'},
  { 'message': 'User', 'translation': 'yonghu', 'language': 'zh'},
  { 'message': 'Sort Editor', 'translation': 'paixubianyiqi', 'language': 'zh'},
  { 'message': 'Home', 'translation': 'zhuye', 'language': 'zh'},
  { 'message': 'State', 'translation': 'zhuangtai', 'language': 'zh'},
  { 'message': 'Preference', 'translation': 'pianai', 'language': 'zh'},
  { 'message': 'Worklists', 'translation': 'gongzhuoliebiao', 'language': 'zh'},
  { 'message': 'Viewable', 'translation': 'shitujiemian', 'language': 'zh'},
  { 'message': 'Language', 'translation': 'yuyan', 'language': 'zh'},
  { 'message': 'Modules', 'translation': 'mokuai', 'language': 'zh'},
  { 'message': 'ascending', 'translation': 'shangshen', 'language': 'zh'},
  { 'message': 'Filter', 'translation': 'guolv', 'language': 'zh'},
  { 'message': 'Searchable Text', 'translation': 'soushuowenben', 'language': 'zh'},
  { 'message': 'Close', 'translation': 'guangbi', 'language': 'zh'},
  { 'message': 'Worklist', 'translation': 'gongzhuoliebiao', 'language': 'zh'},
  { 'message': 'Delete', 'translation': 'shangchu', 'language': 'zh'},
  { 'message': 'keyword', 'translation': 'guanjianchi', 'language': 'zh'},
  { 'message': 'Reference', 'translation': 'chankao', 'language': 'zh'},
  { 'message': 'Filter Editor', 'translation': 'guolvbianjiqi', 'language': 'zh'},
  { 'message': 'Select Template', 'translation': 'xuanzhemoban', 'language': 'zh'},
  { 'message': 'descending', 'translation': 'xiajiang', 'language': 'zh'},
  { 'message': 'Views', 'translation': 'shitu', 'language': 'zh'},
  { 'message': 'Hide Rows', 'translation': 'yanchanlie', 'language': 'zh'},
  { 'message': 'Jump', 'translation': 'tiaozhuan', 'language': 'zh'},
  { 'message': 'Export', 'translation': 'daochu', 'language': 'zh'},
  { 'message': 'Exact Match', 'translation': 'wangquanfuhe', 'language': 'zh'},
  { 'message': 'At lease one (OR)', 'translation': 'zhishaoyige', 'language': 'zh'},
  { 'message': 'Not Less Than', 'translation': 'dayudengyu', 'language': 'zh'},
  { 'message': 'Not Greater Than', 'translation': 'xiaoyudengyu', 'language': 'zh'},
  { 'message': 'Previous', 'translation': 'qianyige', 'language': 'zh'},
  { 'message': 'Web Pages', 'translation': 'wangye', 'language': 'zh'},
  { 'message': 'Draft To Validate', 'translation': 'daiyanzhen', 'language': 'zh'},
  { 'message': 'Foo', 'translation': 'Foo_zhongwen', 'language': 'zh'},
  { 'message': 'Published Alive', 'translation': 'gongbukexiugai', 'language': 'zh'},
  { 'message': 'Chinese', 'translation': 'zhongwen', 'language': 'zh'},
  { 'message': 'Foo Module', 'translation': 'foo_mokuai', 'language': 'zh'},
  { 'message': 'Validate Action', 'translation': 'yanzhen', 'language': 'zh'}
]
for tmp in param_dict:
  context.Base_addUITestTranslation(message = tmp['message'], translation = tmp['translation'], language = tmp['language'])

context.portal_skins.erp5_web_renderjs_ui.Base_getTranslateWordDict()
context.web_site_module.renderjs_runner.setAvailableLanguageSet(['en', 'zh'])

return 'done'
