<?xml version="1.0"?>
<ZopeData>
  <record id="1" aka="AAAAAAAAAAE=">
    <pickle>
      <global name="PythonScript" module="Products.PythonScripts.PythonScript"/>
    </pickle>
    <pickle>
      <dictionary>
        <item>
            <key> <string>Script_magic</string> </key>
            <value> <int>3</int> </value>
        </item>
        <item>
            <key> <string>_bind_names</string> </key>
            <value>
              <object>
                <klass>
                  <global name="NameAssignments" module="Shared.DC.Scripts.Bindings"/>
                </klass>
                <tuple/>
                <state>
                  <dictionary>
                    <item>
                        <key> <string>_asgns</string> </key>
                        <value>
                          <dictionary>
                            <item>
                                <key> <string>name_container</string> </key>
                                <value> <string>container</string> </value>
                            </item>
                            <item>
                                <key> <string>name_context</string> </key>
                                <value> <string>context</string> </value>
                            </item>
                            <item>
                                <key> <string>name_m_self</string> </key>
                                <value> <string>script</string> </value>
                            </item>
                            <item>
                                <key> <string>name_subpath</string> </key>
                                <value> <string>traverse_subpath</string> </value>
                            </item>
                          </dictionary>
                        </value>
                    </item>
                  </dictionary>
                </state>
              </object>
            </value>
        </item>
        <item>
            <key> <string>_body</string> </key>
            <value> <string encoding="cdata"><![CDATA[

"""\n
 This script is part of ERP5 Web\n
\n
 ERP5 Web is a business template of ERP5 which provides a way\n
 to create web sites which can display selected\n
 ERP5 contents through multiple custom web layouts.\n
\n
 This script returns a list of tuples in the form\n
 (title, value) where title is the *translated* title of the\n
 document provided as value. The document value\n
 must be wrapped in the acquisition context\n
 (ex. Web Site / Section / Module / Document).\n
\n
 The reason why the title is generated by this script\n
 is because the layout of a breadcrumb (ex. horizontal,\n
 vertical, tree, etc.) is independent of the kind of\n
 titles we want to use to represent each the breadcrumb\n
 items. It is therefore the responsability of this\n
 script to decide how to identify a document which will\n
 be displayed in a breadcrumb (ex. by title,\n
 by short title, by reference, by version) and to translate\n
 whatever is relevant to be translated.\n
\n
 Page templates which use this script\n
 and need to generate the URLs of document values\n
 should use the getPermanentURL API (called on the\n
 current section) in order to benefit from\n
 virtual hosting features and in order to make sure\n
 that generated URLs are as much as possible permanent\n
 URLs. Never use getUrl or getPath to generate URLs.\n
 You may also use absolute_url but in this case you\n
 will lose all the benefits from permanent URLs.\n
\n
 As a rule of thumb: for viewable content, use\n
 getPermanentURL; for editable content, use absolute_url\n
\n
 This script should be customised if necessary to\n
 implement Web Section specific breadcrumb behaviour.\n
 Typical behaviours include:\n
\n
 - CMS like breadcrumb (hierarchy of contents)\n
 \n
 - Wiki like breadcrumb (history of navigation)\n
 \n
 - or any other behaviour\n
\n
 The default implementation is hierarchical.\n
\n
 Customisation can be portal_type based, class based\n
 or can simply result from putting a WebSection_getBreadcrumbItemList\n
 directly inside a given section rather than in a skin\n
 folder. The later is recommended for hosting\n
 multiple sites on a single ERP5Site instance.\n
"""\n
from zExceptions import Unauthorized\n
if document is None: document = context\n
crumb_list = []\n
\n
# Implementation consists in browsing the aq_parent sequence\n
web_site = context.getWebSiteValue()\n
chain_list = document.Base_getAcquisitionParentValueList(upper_portal_type=\'Web Site\')\n
chain_list.reverse()\n
\n
last_breadcrumb_offset = 1\n
max_breadcrumb_length = web_site.getLayoutProperty(\'layout_max_breadcrumb_length\', None)\n
chain_list_length = len(chain_list)\n
\n
is_web_section_default_document = bool(context.REQUEST.get(\'is_web_section_default_document\', False))\n
if is_web_section_default_document:\n
  last_breadcrumb_offset = 2\n
\n
for chain_index in xrange(0, chain_list_length):\n
  try:\n
    crumb = chain_list[chain_index]\n
    if chain_index == 0:\n
      title = context.Base_translateString(\'Home\')\n
    else:\n
      title = crumb.Base_getTitle()\n
  except Unauthorized:\n
    # We should ignore any item in the chain which raises \n
    # a security exception. We use a catchall except here\n
    # because there is no way to import Unauthorized permission\n
    title = None\n
\n
  if title is not None:\n
    full_title = title\n
    # shorten it only if it exceeds maximum specified length or\n
    # not last element in breadcrumb (include default Web Page which is not show but part of chain_list)\n
    if max_breadcrumb_length is not None and \\\n
       (chain_index + last_breadcrumb_offset < chain_list_length) and \\\n
       (len(title) - 4 > max_breadcrumb_length):\n
      title = \'%s ...\' %(title[:max_breadcrumb_length])\n
    crumb_list.append((title, crumb, full_title))\n
\n
return crumb_list\n


]]></string> </value>
        </item>
        <item>
            <key> <string>_params</string> </key>
            <value> <string>document=None</string> </value>
        </item>
        <item>
            <key> <string>id</string> </key>
            <value> <string>WebSection_getBreadcrumbItemList</string> </value>
        </item>
      </dictionary>
    </pickle>
  </record>
</ZopeData>
