preference = context.portal_preferences.accounting_zuite_preference
preference.setPreferredAccountingTransactionSectionCategory(None)
preference.setPreferredSectionCategory(None)

return str((preference.getPreferredSectionCategory(), preference.getPreferredAccountingTransactionSectionCategory()))
