"""
  Return the configuration used during test.
"""
from DateTime import DateTime

return {'now': DateTime(),

        'person_howto_title': 'John Doh',
        'person_howto_first_name': 'John',
        'person_howto_last_name': 'Doh',
        'person_howto_gender': 'Male',
        'person_howto_role': 'Client',
        'person_howto_career_function': 'Marketing/Marketing Manager',
        'person_howto_career_activity': 'Education',
        'person_howto_nationality': 'French',
        'person_howto_email': 'jdoh@zcompany.com',
        'person_howto_telephone': '+33(0)6-218765/00',
        'person_howto_reference': 'johndoh',
        'person_howto_password': 'secret',

        'person_howto_title2': 'ZUITE-TEST-PERSON2 USER-002',
        'person_howto_first_name2': 'ZUITE-TEST-PERSON2',
        'person_howto_last_name2': 'USER-002',
        'person_howto_email2': 'USER-002@test.com',
        'person_howto_organisation_title': 'Z Company',

        'organisation_howto_organisation_title': 'Z Company',
        'bankaccount_howto_organisation_title': 'HSBC Enterprise',

        'link_howto_person_title' : 'ZUITE-TEST-LINK USER-001',
        'link_howto_person_first_name': 'ZUITE-TEST-LINK',
        'link_howto_person_last_name': 'USER-001',
        'link_howto_organisation_title': 'ZUITE-TEST-LINK-ORGANISATION-001',
        'link_howto_organisation2_title': 'ZUITE-TEST-LINK-ORGANISATION-002',
        'product_howto_product_title': 'ZUITE-TEST-PRODUCT-PRODUCT-001',
        'product_howto_organisation_title': 'ZUITE-TEST-PRODUCT-ORGANISATION-001',
        'product_howto_currency_title': 'Euro',
        'product_howto_currency_tag': 'EUR',
        'sale_howto_product_title': 'ZUITE-TEST-SALEORDER-PRODUCT-001',
        'sale_howto_organisation_title': 'ZUITE-TEST-SALEORDER-ORGANISATION-001',
        'sale_howto_bank_account_title': 'Main account',
        'sale_howto_bank_account_reference': '0123456789 0123456789',
        'sale_howto_organisation2_title': 'ZUITE-TEST-SALEORDER-ORGANISATION-002',
        'sale_howto_organisation3_title': 'ZUITE-TEST-SALEORDER-ORGANISATION-003',
        'sale_howto_person_title': 'ZUITE-TEST-SALEORDER USER-001',
        'sale_howto_payment_title': 'ZUITE-TEST-SALEORDER-PAYMENT-TRANSACTION-001',
        'sale_howto_currency_title': 'Euro',
        'sale_howto_currency_tag': 'EUR',
        'sale_howto_product_reference': 'ZUITE-TEST-SALEORDER-RL01',
        'sale_howto_trade_condition_title': 'ZUITE-TEST-SALE-TRADE-CONDITION-001',
        'sale_howto_sale_order_title': 'ZUITE-TEST-TRADE-CONDITION-SALE-ORDER-001',
        'campaign_howto_person_title': 'ZUITE-TEST-CAMPAIGN-PERSON-SUPERVISOR',
        'campaign_howto_person2_title': 'ZUITE-TEST-CAMPAIGN-PERSON-OPERATION-MANAGER',
        'campaign_howto_organisation_title': 'ZUITE-TEST-CAMPAIGN-ORGANISATION-001',
        'campaign_howto_currency_title': 'Euro',
        'campaign_howto_currency_tag': 'EUR',
        'campaign_howto_campaign_title': 'ZUITE-TEST-CAMPAIGN-CAMPAIGN-001',
        'campaign_howto_campaign_reference': 'ZUITE-TEST-CAMPAIGN-CAMPAIGN-001',
        'create_event_howto_person_title': 'ZUITE-TEST-CREATE-EVENT-PERSON-SUPERVISOR',
        'create_event_howto_person2_title': 'ZUITE-TEST-CREATE-EVENT-PERSON-OPERATION-MANAGER',
        'create_event_howto_person_email': 'me@erp5.org',
        'create_event_howto_person2_email': 'me@erp5.org',
        'create_event_howto_organisation_title': 'ZUITE-TEST-CREATE-EVENT-ORGANISATION-001',
        'create_event_howto_currency_title': 'Euro',
        'create_event_howto_currency_tag': 'EUR',
        'create_event_howto_campaign_title': 'ZUITE-TEST-CREATE-EVENT-CAMPAIGN-001',
        'create_event_howto_campaign_reference': 'ZUITE-TEST-CREATE-EVENT-CAMPAIGN-001',
        'create_event_howto_event_title': 'ZUITE-TEST-CREATE-EVENT-EVENT-001',
        'create_event_howto_event_description': 'ZUITE-TEST--CREATE-EVENT-EVENT-DESCRIPTION this is a test event !',
        'create_event_howto_event_content': 'ZUITE-TEST-CREATE-EVENT-EVENT-CONTENT this is the content of our event.',
        'post_event_howto_person_title': 'ZUITE-TEST-POST-EVENT-PERSON-SUPERVISOR',
        'post_event_howto_person2_title': 'ZUITE-TEST-POST-EVENT-PERSON-OPERATION-MANAGER',
        'post_event_howto_person_email': 'lucas@nexedi.com',
        'post_event_howto_person2_email': 'lucas@nexedi.com',
        'post_event_howto_organisation_title': 'ZUITE-TEST-POST-EVENT-ORGANISATION-001',
        'post_event_howto_currency_title': 'Euro',
        'post_event_howto_currency_tag': 'EUR',
        'post_event_howto_campaign_title': 'ZUITE-TEST-POST-EVENT-CAMPAIGN-001',
        'post_event_howto_campaign_reference': 'ZUITE-TEST-POST-EVENT-CAMPAIGN-001',
        'post_event_howto_event_title': 'ZUITE-TEST-POST-EVENT-EVENT-001',
        'post_event_howto_event_description': 'ZUITE-TEST-POST-EVENT-EVENT-DESCRIPTION this is a test event !',
        'post_event_howto_event_content': 'ZUITE-TEST-POST-EVENT-EVENT-CONTENT this is the content of our event.',

        'incoming_event_howto_service_id': 'test_functional_incoming_service',
        'incoming_event_howto_service_title': 'Test Functional Incoming Service',
        'incoming_event_howto_person_title': 'ZUITE-TEST-INCOMING-EVENT-PERSON-SUPERVISOR',
        'incoming_event_howto_person2_title': 'ZUITE-TEST-INCOMING-EVENT-PERSON-OPERATION-MANAGER',
        'incoming_event_howto_person_email': 'lucas@nexedi.com',
        'incoming_event_howto_person2_email': 'lucas@nexedi.com',
        'incoming_event_howto_organisation_title': 'ZUITE-TEST-INCOMING-EVENT-ORGANISATION-001',
        'incoming_event_howto_currency_title': 'Euro',
        'incoming_event_howto_currency_tag': 'EUR',
        'incoming_event_howto_campaign_title': 'ZUITE-TEST-INCOMING-EVENT-CAMPAIGN-001',
        'incoming_event_howto_campaign_reference': 'ZUITE-TEST-INCOMING-EVENT-CAMPAIGN-001',
        'incoming_event_howto_event_title': 'ZUITE-TEST-INCOMING-EVENT-EVENT-001',
        'incoming_event_howto_event_description': 'ZUITE-TEST-INCOMING-EVENT-EVENT-DESCRIPTION this is a test event !',
        'incoming_event_howto_event_content': 'ZUITE-TEST-EVENT-CONTENT this is the content of our event.',
        'incoming_event_howto_ticket_title': 'ZUITE-TEST-INCOMING-EVENT-TICKET-TITLE-001',
        'incoming_event_howto_ticket_comment': 'ZUITE-TEST-INCOMING-EVENT-TICKET-COMMENT This is a comment of a ticket',
        'incoming_event_howto_ticket_content': 'ZUITE-TEST-INCOMING-EVENT-TICKET-CONTENT This is the content of the ticket',

        'outgoing_event_howto_person_title': 'ZUITE-TEST-OUTGOING-EVENT-PERSON-SUPERVISOR',
        'outgoing_event_howto_person2_title': 'ZUITE-TEST-OUTGOING-EVENT-PERSON-OPERATION-MANAGER',
        'outgoing_event_howto_person_email': 'lucas@nexedi.com',
        'outgoing_event_howto_person2_email': 'lucas@nexedi.com',
        'outgoing_event_howto_organisation_title': 'ZUITE-TEST-OUTGOING-EVENT-ORGANISATION-001',
        'outgoing_event_howto_currency_title': 'Euro',
        'outgoing_event_howto_currency_tag': 'EUR',
        'outgoing_event_howto_campaign_title': 'ZUITE-TEST-OUTGOING-EVENT-CAMPAIGN-001',
        'outgoing_event_howto_campaign_reference': 'ZUITE-TEST-OUTGOING-EVENT-CAMPAIGN-001',
        'outgoing_event_howto_event_title': 'ZUITE-TEST-OUTGOING-EVENT-EVENT-001',
        'outgoing_event_howto_event_description': 'ZUITE-TEST-OUTGOING-EVENT-EVENT-DESCRIPTION this is a test event !',
        'outgoing_event_howto_event_content': 'ZUITE-TEST-OUTGOING-EVENT-EVENT-CONTENT this is the content of our event.',
        'outgoing_event_howto_ticket_title': 'ZUITE-TEST-OUTGOING-EVENT-TICKET-TITLE-001',
        'outgoing_event_howto_ticket_comment': 'ZUITE-TEST-OUTGOING-EVENT-TICKET-COMMENT This is a comment of a ticket',
        'outgoing_event_howto_ticket_content': 'ZUITE-TEST-OUTGOING-EVENT-TICKET-CONTENT This is the content of the ticket',
        'howto_preference_id': 'zuite_erp5_ui_test_preference',
        'howto_system_preference_id': 'zuite_erp5_ui_test_system_preference',
        'full_text_person_title': 'ZUITE_TEST_FULL_TEXT_PERSON_TITLE_001',
        'full_text_person_reference': 'ZUITE_TEST_FULL_TEXT_PERSON_REFERENCE_001',
        'full_text_person_email': 'ZUITE_TEST_FULL_TEXT_PERSON_REFERENCE_001@tiolive.com',
        'full_text_organisation_title': 'ZUITE_TEST_FULL_TEXT_ORGANISATION_TITLE_001',
        'full_text_organisation_email': 'ZUITE_TEST_FULL_TEXT_ORGANISATION_EMAIL@tiolive.com',
        'optional_new_accounting_period_title': 'ZUITE_OPTIONAL_NEW_ACCOUNTING_PERIOD',
        'dig_currency_title': 'ZUITE_TEST_DIG_EURO',

        'functional_test_username' : 'functional_test_username',
        'functional_another_test_username' : 'functional_another_test_username',
        'functional_test_user_password' : 'secret',
        'functional_test_user_email': 'lucas@nexedi.com',
        }
