url_list = [
  "gadget_erp5_page_drone_simulator_logic_comparison.js",
  "gadget_erp5_page_ui_flight_comparison_script_page.html",
  "gadget_erp5_page_ui_flight_comparison_script_page.js",
  "gadget_erp5_page_ui_flight_comparison_log_page.html",
  "gadget_erp5_page_ui_flight_comparison_log_page.js",
  "gadget_erp5_page_drone_simulator_main.js",
  "gadget_erp5_page_flight_comparison_gadget.html",
  "gadget_erp5_page_flight_comparison_gadget.js",
  "gadget_erp5_page_drone_simulator_web_worker.js",
  "gadget_erp5_panel_drone_simulator.html",
  "gadget_erp5_panel_drone_simulator.js",
  "gadget_erp5_page_flight_comparison_droneaaailefixe.js",
  "gadget_erp5_page_flight_comparison_dronelogfollower.js",
  "babylon.js",
  "drone.png",
  "babylon.gui.js",
  "gadget_officejs_drone_simulator.json",
  "assets/map/terrain.jpg",
  "assets/map/map.babylon",
  "assets/drone/drone.babylon",
  "assets/drone/drone_bleu.jpg",
  "assets/drone/drone_bleu_old.jpg",
  "assets/drone/drone_rouge.jpg",
  "assets/drone/drone_rouge_old.jpg",
  "assets/skybox/sky_nx.jpg",
  "assets/skybox/sky_ny.jpg",
  "assets/skybox/sky_nz.jpg",
  "assets/skybox/sky_px.jpg",
  "assets/skybox/sky_py.jpg",
  "assets/skybox/sky_pz.jpg",
  "gadget_erp5_notification.html"
]

return url_list
