context.logEntry("Alarm_dataLakeHandleAnalysis FIRED!")
portal = context.getPortalObject()
portal.DataLake_stopIngestionList()
portal.DataLake_createDataAnalysisList()
portal.DataLake_executeDataAnalysisList()
