from Constraint import Constraint
from PropertyTypeValidity import PropertyTypeValidity
from CategoryMembershipArity import CategoryMembershipArity
from CategoryRelatedMembershipArity import CategoryRelatedMembershipArity
from AttributeEquality import AttributeEquality